version: '3.7'
services:
  api-spotify:
    container_name: api-divisors-numbers
    build:
      context: .
      dockerfile: DockerFile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8080:8080'